/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("product").del();

  await knex("product").insert([
    {
      uniqueid: "1",
      name: "Fresh Pork",
      description: "1kg Fresh Pork",
      price: 10,
      imagepath: "/Assets/Images/Red meat.jpg",
      cateid: "M01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "2",
      name: "Chicken Breast",
      description: "500g Chicken Breast",
      price: 7,
      imagepath: "/Assets/Images/Red meat.jpg",
      cateid: "M01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "3",
      name: "Salmon Fillet",
      description: "500g Fresh Salmon",
      price: 15,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "4",
      name: "Shrimps",
      description: "1kg Shrimps",
      price: 12,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "5",
      name: "Whole Milk",
      description: "1L Fresh Whole Milk",
      price: 3,
      imagepath: "/Assets/Images/milk.png",
      cateid: "Mk01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "6",
      name: "Skimmed Milk",
      description: "1L Skimmed Milk",
      price: 2.5,
      imagepath: "/Assets/Images/milk.png",
      cateid: "Mk01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "7",
      name: "Broccoli",
      description: "500g Fresh Broccoli",
      price: 4,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "8",
      name: "Carrots",
      description: "1kg Fresh Carrots",
      price: 3,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "9",
      name: "Spinach",
      description: "500g Fresh Spinach",
      price: 5,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "10",
      name: "Tomatoes",
      description: "1kg Fresh Tomatoes",
      price: 4,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "11",
      name: "Ground Beef",
      description: "500g Ground Beef",
      price: 9,
      imagepath: "/Assets/Images/Red meat.jpg",
      cateid: "M01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "12",
      name: "Yogurt",
      description: "500g Yogurt",
      price: 6,
      imagepath: "/Assets/Images/milk.png",
      cateid: "Mk01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "13",
      name: "Shrimp Paste",
      description: "500g Shrimp Paste",
      price: 10,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "14",
      name: "Cucumber",
      description: "1kg Fresh Cucumber",
      price: 3,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "15",
      name: "Tofu",
      description: "500g Fresh Tofu",
      price: 4,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "16",
      name: "Cod Fillet",
      description: "500g Cod Fillet",
      price: 13,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "17",
      name: "Face Cream",
      description: "50ml Face Cream",
      price: 20,
      imagepath: "/Assets/Images/kemps.jpg",
      cateid: "BH01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "18",
      name: "Shampoo",
      description: "500ml Hair Shampoo",
      price: 8,
      imagepath: "/Assets/Images/kemps.jpg",
      cateid: "BH01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "19",
      name: "Body Lotion",
      description: "500ml Body Lotion",
      price: 10,
      imagepath: "/Assets/Images/kemps.jpg",
      cateid: "BH01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "20",
      name: "Salmon Roe",
      description: "100g Fresh Salmon Roe",
      price: 30,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "21",
      name: "Grilled Chicken Breast",
      description: "1kg Grilled Chicken Breast",
      price: 20,
      imagepath: "/Assets/Images/Red meat.jpg",
      cateid: "M01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "22",
      name: "Beef Tenderloin",
      description: "500g Beef Tenderloin",
      price: 12,
      imagepath: "/Assets/Images/Red meat.jpg",
      cateid: "M01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "23",
      name: "Pork Chops",
      description: "2kg Pork Chops",
      price: 32,
      imagepath: "/Assets/Images/Red meat.jpg",
      cateid: "M01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "24",
      name: "Ground Turkey",
      description: "300g Ground Turkey",
      price: 10,
      imagepath: "/Assets/Images/Red meat.jpg",
      cateid: "M01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "25",
      name: "Lamb Shanks",
      description: "1kg Lamb Shanks",
      price: 18,
      imagepath: "/Assets/Images/Red meat.jpg",
      cateid: "M01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "26",
      name: "Salmon Fillet",
      description: "2kg Fresh Salmon Fillet",
      price: 30,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "27",
      name: "Shrimp Scampi",
      description: "400g Fresh Shrimp Scampi",
      price: 20,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "28",
      name: "Mahi-Mahi",
      description: "1kg Mahi-Mahi",
      price: 21,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "29",
      name: "Tuna Steak",
      description: "800g Tuna Steak",
      price: 10,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "30",
      name: "Crab Cakes",
      description: "1kg Crab Cakes",
      price: 6,
      imagepath: "/Assets/Images/fish.jpg",
      cateid: "SF01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "31",
      name: "Organic Spinach",
      description: "500g Organic Spinach",
      price: 5,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "32",
      name: "Sweet Potatoes",
      description: "700g Sweet Potatoes",
      price: 12,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "33",
      name: "Bell Peppers",
      description: "500g Bell Peppers",
      price: 8,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "34",
      name: "Zucchini",
      description: "200g Zucchini",
      price: 4,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "35",
      name: "Durian",
      description: "4kg Durian",
      price: 17,
      imagepath: "/Assets/Images/veget.png",
      cateid: "Vet01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "36",
      name: "Soy Milk",
      description: "300ml Soy Milk",
      price: 6,
      imagepath: "/Assets/Images/milk.png",
      cateid: "Mk01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "37",
      name: "Skim Milk",
      description: "2000ml Skim Milk",
      price: 16,
      imagepath: "/Assets/Images/milk.png",
      cateid: "Mk01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "38",
      name: "Coconut Milk",
      description: "500ml Coconut Milk",
      price: 4,
      imagepath: "/Assets/Images/milk.png",
      cateid: "Mk01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "39",
      name: "Oat Milk",
      description: "500ml Oat Milk",
      price: 13,
      imagepath: "/Assets/Images/milk.png",
      cateid: "Mk01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "40",
      name: "Almond Milk",
      description: "400ml Almond Milk",
      price: 8,
      imagepath: "/Assets/Images/milk.png",
      cateid: "Mk01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "41",
      name: "Moisturizing Facial Cream",
      description: "A nourishing cream that hydrates and softens the skin.",
      price: 10,
      imagepath: "/Assets/Images/kemps.jpg",
      cateid: "BH01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "42",
      name: "Coconut Oil",
      description: "500ml Coconut Oil",
      price: 10,
      imagepath: "/Assets/Images/kemps.jpg",
      cateid: "BH01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "43",
      name: "Organic Green Tea",
      description: "Rich in antioxidants, this herbal tea promotes health ",
      price: 18,
      imagepath: "/Assets/Images/kemps.jpg",
      cateid: "BH01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "44",
      name: "Herbal Hair Shampoo",
      description: "Gentle shampoo that cleanses and nourishes the hair",
      price: 12,
      imagepath: "/Assets/Images/kemps.jpg",
      cateid: "BH01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
    {
      uniqueid: "45",
      name: "Vitamin C Serum",
      description: "A brightening serum",
      price: 6,
      imagepath: "/Assets/Images/kemps.jpg",
      cateid: "BH01",
      stock: 100,
      status: true,
      orderquantity: 0,
    },
  ]);
};
