/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("voucher").del();
  await knex("voucher").insert([
    {
      uniqueid: "VCHR001",
      name: "Discount 10%",
      description: "10% off on all items",
      percent: "10",
      amount: null,
      condition: 0,
      stock: 100,
      validate: "2024-12-31",
      rankid: "R01",
    },
    {
      uniqueid: "VCHR002",
      name: "Discount 20%",
      description: "20% off on selected items",
      percent: "20",
      amount: null,
      condition: 0,
      stock: 50,
      validate: "2024-12-31",
      rankid: "R02",
    },
    {
      uniqueid: "VCHR003",
      name: "New Year Special",
      description: "Special voucher for New Year",
      percent: "15",
      amount: null,
      condition: 0,
      stock: 30,
      validate: "2024-12-31",
      rankid: "R01",
    },
    {
      uniqueid: "VCHR004",
      name: "Cashback $10",
      description: "Get $10 cashback",
      percent: null,
      amount: 10,
      condition: 100,
      stock: 20,
      validate: "2024-12-31",
      rankid: "R03",
    },
    {
      uniqueid: "VCHR005",
      name: "VIP Discount 25%",
      description: "25% off for VIP members",
      percent: "25",
      amount: null,
      condition: 50,
      stock: 10,
      validate: "2024-12-31",
      rankid: "R04",
    },
    {
      uniqueid: "VCHR006",
      name: "Free Shipping",
      description: "Free shipping on orders above $50",
      percent: null,
      amount: 0,
      condition: 50,
      stock: 100,
      validate: "2024-12-31",
      rankid: "R01",
    },
    {
      uniqueid: "VCHR007",
      name: "Buy 1 Get 1",
      description: "Buy one, get one free",
      percent: null,
      amount: 0,
      condition: 0,
      stock: 50,
      validate: "2024-12-31",
      rankid: "R05",
    },
    {
      uniqueid: "VCHR008",
      name: "Flash Sale",
      description: "Limited time flash sale",
      percent: "30",
      amount: null,
      condition: 100,
      stock: 15,
      validate: "2024-12-31",
      rankid: "R02",
    },
    {
      uniqueid: "VCHR009",
      name: "Exclusive 5%",
      description: "5% off for exclusive members",
      percent: "5",
      amount: null,
      condition: 0,
      stock: 70,
      validate: "2024-12-31",
      rankid: "R03",
    },
    {
      uniqueid: "VCHR010",
      name: "Holiday Special",
      description: "Special discount for holidays",
      percent: null,
      amount: 20,
      condition: 200,
      stock: 25,
      validate: "2024-12-31",
      rankid: "R04",
    },
  ]);
};
